### ISSUE TITLE
threadMode = ThreadMode.MAIN UI is not updating

### ISSUE THREAD

**Issue by sripati** [greenrobot/EventBus#588] opened 2019-06-06 14:55 UTC
I am posting the event from Main thread and I have subscribed as a ThreadMode.MAIN. My subscribed method is calling but UI is not updating. I want to update the progress status.

Class : Post Event Sample Code:
--------------------------
for(int i = 0; i < 10; i++) {
// Doing some operation
EventBus.getDefault().post(new MySample(i));
}

Activity : Subscribed Sample Code:
--------------------------
@Subscribe(threadMode = ThreadMode.MAIN)
public void updateUI(MySample event) {
   //Updating UI
}

Here updateUI() is calling, but UI is not updating. Please help me with this.
Event Bus Version: 3.1.1

Note: If I will post the event from a background thread, UI is updating.

Thank you,

**Comment by Zhuinden** [comment] 2019-06-16 17:00
you need to register to the bus to make the `@Subscribe` annotated methods be called

**Comment by sripati** [comment] 2019-06-16 17:13
Thank you for the response. I have registered already and updateUI() is calling as well. The problem is inside updateUI() my TextView or toast message is not updating/showing. Maybe I did not get you what you are trying to explain. Really I will appreciate getting the help as soon as possible.

Thanks in advance.

**Comment by greenrobot-team** [comment] 2019-06-18 13:12
@sripati Without a more complete example I guess we just don't know what you are trying to do.
-Uwe

**Comment by ggyg123** [comment] 2019-06-30 02:51
I'm setting up a state and putting the code to update the Ui in the onResume method and updating the Ui based on the state in the onResume method

**Comment by greenrobot-team** [comment] 2019-07-16 08:23
@ggyg123 Do you have the same issue as @sripati? Could you please share a minimal code example and what the issue is?

**Comment by sakuraso13** [comment] 2019-07-21 04:45
Maybe you do the registration after you do the post. @sripati

**Comment by Zhuinden** [comment] 2019-07-21 19:08
If you unregister in `onPause`, then system dialogs and runtime permission dialogs invoke `onPause` and make you unregister.

**Comment by sunreview** [comment] 2023-03-16 07:48
maybe u should use sticky event(post before subscribe)

**Comment by greenrobot-team** [comment] 2023-03-27 12:14
Closing as original posters have not replied for a long time.

**Closed by greenrobot-team** 2023-03-27 12:14 UTC
Labels: more info required
