### ISSUE TITLE
    java.lang.RuntimeException: Unable to start activity ComponentInfo: m.d.a.g: Subscriber class  and its super classes have no public methods with the @Subscribe annotation

### ISSUE THREAD

**Issue by Oreses-Tech** [greenrobot/EventBus#648] opened 2020-07-09 10:02 UTC
I am getting this error when "minifyEnabled true".

**Comment by greenrobot-team** [comment] 2020-07-13 05:48
Duplicate of #649.

**Closed by greenrobot-team** 2020-07-13 05:48 UTC
