### ISSUE TITLE
Hope new feature:postDelay(event,delayTimeMilli)

### ISSUE THREAD

**Issue by edwardZj** [greenrobot/EventBus#349] opened 2016-08-31 08:29 UTC
Hope new feature:postDelay(event,delayTimeMilli)
new method like this:EventBus.getDefault().postDelay(event,delayTimeMilli);
the event can be received after delayTimeMilli millisecond,
and this method can be useful

**Comment by keluokeda** [comment] 2016-09-11 14:02
so i am,like  handle postDelay

**Comment by greenrobot-team** [comment] 2016-09-19 08:24
Duplicate of #70. -ut

**Closed by greenrobot-team** 2016-09-19 08:24 UTC
