### ISSUE TITLE
[BUG][CRITICAL] R8 will delete all @Subscribe methods

### ISSUE THREAD

**Issue by Duna** [greenrobot/EventBus#625] opened 2019-12-29 10:25 UTC
All @Subscribe methods gets deleted by using R8, no matter of proguard rules. All subscribe methods are public.

```
shrinkResources true
minifyEnabled true
```

Proguard rules:

```
-keepattributes *Annotation*
-keepclassmembers class * {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }

# Only required if you use AsyncExecutor
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}
```

This bug is critical since EventBus is no longer working with newest Android technologies

**Comment by greenrobot-team** [comment] 2020-01-21 06:55
Thanks for reporting. This is a duplicate of #586.

**Closed by greenrobot-team** 2020-01-21 06:55 UTC

**Comment by Duna** [comment] 2020-04-01 11:26
Still anyone facing the issue? How did you solved it?
gradle.properties: `android.enableR8 = true`
gradle file:
```
        debug {
            minifyEnabled true
            shrinkResources false
            signingConfig signingConfigs.config
        }
```

**Comment by Duna** [comment] 2020-04-01 15:39
The EventBus team should add proguard rules as OkHttp does: [OkHttp.pro](https://github.com/square/okhttp/blob/master/okhttp/src/main/resources/META-INF/proguard/okhttp3.pro) Waiting for a new release till then.

**Comment by Duna** [comment] 2020-04-01 15:42
https://square.github.io/okhttp/r8_proguard/ look what others do
