### ISSUE TITLE
EventBus.getDefault (). Isregistered (this) method is invalid

### ISSUE THREAD

**Issue by hanfeiyu1** [greenrobot/EventBus#650] opened 2020-07-14 00:24 UTC
Eventbus.getdefault ().isregistered (this) returns false when plug-in APK (loaded by classLoader) USES eventbus.getdefault ().isregistered (this) to determine if EventBus isregistered, even if I have registered previously.

**Comment by greenrobot-team** [comment] 2020-07-14 05:36
Have a look at the source code what might be the issue. You might also provide an example project reproducing this.

**Comment by sunreview** [comment] 2023-03-15 16:58
` public void register(Object subscriber) {
        if (AndroidDependenciesDetector.isAndroidSDKAvailable() && !AndroidDependenciesDetector.areAndroidComponentsAvailable()) {
            // Crash if the user (developer) has not imported the Android compatibility library.
            throw new RuntimeException("It looks like you are using EventBus on Android, " +
                    "make sure to add the \"eventbus\" Android library to your dependencies.");
        }

        Class<?> subscriberClass = subscriber.getClass();
        List<SubscriberMethod> subscriberMethods = subscriberMethodFinder.findSubscriberMethods(subscriberClass);
        Collections.sort(subscriberMethods);
        synchronized (this) {
            for (SubscriberMethod subscriberMethod : subscriberMethods) {
                subscribe(subscriber, subscriberMethod);
            }
        }
    }`
look at this code,maybe it 's because there 's no @subscribe method in your registered class.so it won't execute the subscribe method

**Comment by greenrobot-team** [comment] 2023-03-27 12:44
The original poster has not replied in a long time. Closing this.

**Closed by greenrobot-team** 2023-03-27 12:44 UTC
