### ISSUE TITLE
How does the code segment in HandlerPoster work?

### ISSUE THREAD

**Issue by realxz** [greenrobot/EventBus#612] opened 2019-10-11 17:11 UTC
```
if (timeInMethod >= maxMillisInsideHandleMessage) {
    if (!sendMessage(obtainMessage())) {
        throw new EventBusException("Could not send handler message");
    }
    rescheduled = true;
    return;
}  
```

I think deleting this code will have no effect and the program will still work. #369

**Comment by fox-zhw** [comment] 2022-12-07 06:16
Avoid blocking the main thread for long periods of time so that system messages cannot be executed in a timely manner

**Comment by greenrobot-team** [comment] 2022-12-12 07:12
Duplicate of #369

**Closed by greenrobot-team** 2022-12-12 07:12 UTC
