### ISSUE TITLE
EventBus multiplying messages by count of Activities

### ISSUE THREAD

**Issue by Mattue** [greenrobot/EventBus#442] opened 2017-06-21 16:30 UTC
Hello!
I'm using EventBus and have some misunderstandings how to use it.

In my app, I have 4 activities: MainActivity and 3 other. Each Activity have it's own role in app, and MainActivity holds connection via COM port and sends/receives messages. So, when message is received, it sends via EventBus to current working activity. And when other Activity needs to sent message to COM port, it sending message to MainActivity via EventBus too. Problem is that when I'm working in one activity - all works fine, but when I try to do something in other activities - messages from EventBus are duplicaed. There is more - when I try to work in third activity - message is multiplies by 3 and so on.

Here some code:

    public class ManualControl extends AppCompatActivity 
    {
     @Override
     protected void onCreate(Bundle savedInstanceState) 
     {
         super.onCreate(savedInstanceState);
         //my other code here
     }
    
     @Override
     protected void onPause()
     {
         super.onPause();
         EventBus.getDefault().unregister(this);
     } 

     @Override
     public void onResume()
     {
         super.onResume();
         EventBus.getDefault().register(this);
     }

     @Subscribe(threadMode = ThreadMode.MAIN)
     public void onEvent(MessageEventFromMain event)
     {
      //code to do when get message from MainActivity
     };    

     private void sendMessage(String messageID, String messageName)
     {
         EventBus.getDefault().post(new MessageEventFromIntent(messageID, messageName));
     }
    }

This method I use to send message to another Activity from MainActivity

        EventBus.getDefault().post(new MessageEventFromMain(messageFromSerial));

And catch event from other Activities in MainActivity

        @Subscribe(threadMode = ThreadMode.MAIN)
        public void onMessageEventFromIntent(MessageEventFromIntent event)
        {
         //code to do when get message from intent
        }

As you can see, I'm unregistering onPause() and registering onResume(), but when I'm closing this activity and starting it again messages are duplicating.

Example:

1st use:

        55017031011_TURN_STRAIGHT27

2nd use:

        55017031011_TURN_STRAIGHT2755017031011_TURN_STRAIGHT27

**Comment by Mattue** [comment] 2017-06-21 17:23
I suspect that the problem is that when I open Activity and try to send message it's creating new MessageEventFromIntent object via "new MessageEventFromIntent" method, and not deletes it when Activity is closing.

**Comment by Mattue** [comment] 2017-06-21 17:30
Unregister MainActivity from MessageEventFromIntent event after Activity is closed?

**Comment by Mattue** [comment] 2017-06-21 18:28
[http://i.imgur.com/K6zEQ3L.png](screenshot) 
Just cheked with HPROF Viewer Display. Problem that object MessageFromIntent is not deleating after cloasing Activity.

**Comment by greenrobot-team** [comment] 2017-06-26 06:50
@Mattue Check that your `MessageFromIntent` class or anything in your activities is not holding onto the activity and keeping it alive. Also you should not be able to send messages between activities, as no two activities can be resumed at the same time. In that case you may want to [use sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/).
-ut

**Comment by ikscn** [comment] 2017-07-07 12:03
Hi, I'm struggling with the same issue as @Mattue's...
My app is working on Xiaomi MiBox 3, and it should usually run 24/7.
I have:
- a **MainActivity** as EventBus **subscriber**, registered by onResume() after the service is started, unregistered by onStop()
- a **Service** as EventBus **message sender**, started by onResume() in my MainActivity, stopped by onPause()

When the app is paused/stopped and resumed after a while, sometimes the messages sent by the service is duplicated, and this cause a big issue on my tasks working with these messages.
I am thinking about to register EventBus before starting the service. Do you think that would make a difference? I cannot test it easily because the issue could show up after days..

My code looks like following:

MainActivity:
`@Override
    protected void onResume() {`
`// Start MyService
            Intent myIntent = new Intent(getBaseContext(), MyService.class);
            getApplicationContext().startService(myIntent);
            EventBus.getDefault().register(this);`
`}`
...
`protected void onStop() {
        super.onStop();
        EventBus.getDefault().unregister(this);
 }`
...
`@Override
    protected void onPause() {

        if(mBoundDbService) {
            getApplicationContext().unbindService(mDbConnection);
            mBoundDbService = false;
        }

        getApplicationContext().stopService(new Intent(getBaseContext(), MyService.class));

        super.onPause();
}`

**Comment by Mattue** [comment] 2017-07-07 13:13
@ikscn. About my problem - I had a handler that registers and never unregisters. I thought that this handler must work all time of app working, so I dont need to unregister it. But you really need to unregister all you'r classes inspite of that this class is always active. I'm unregistering my in "onDestroy" of MainActivity. Try this. But if you are trying to subscribe class that not exists - use stiky events.

**Comment by greenrobot-team** [comment] 2017-07-10 05:37
@ikscn You should unregister [in the same lifecycle level, in this case `onPause()`](https://developer.android.com/guide/components/activities/activity-lifecycle.html#alc). Otherwise the activity may be paused, then immediately resumed, causing it to be registered again without unregistering first. -ut

**Comment by greenrobot-team** [comment] 2017-07-10 05:38
Closing as @Mattue issue was resolved (and was not a bug with EventBus). -ut

**Closed by greenrobot-team** 2017-07-10 05:38 UTC
