### ISSUE TITLE
R8 @subscribe annotation

### ISSUE THREAD

**Issue by pcg92** [greenrobot/EventBus#586] opened 2019-05-25 23:40 UTC
Im getting the "classic" error using this library with proguard, but now with r8  the "classic" solution https://stackoverflow.com/a/39387526/3994630 is not working.
Any idea?

**Comment by greenrobot-team** [comment] 2019-05-27 12:11
R8 should use the same rule format as ProGuard. Can you verify your build works by turning off R8?
https://developer.android.com/studio/releases/gradle-plugin#behavior_changes

If yes, file a bug report for R8 as mentioned in the above release notes.
-Uwe

**Comment by pcegarra** [comment] 2019-05-27 21:09
Turning off R8 the app is working nice

**Comment by Zhangshua** [comment] 2019-06-05 09:27
I have same issues. Using proguard is OK, using R8 not work. 
Error info：
java.lang.annotation.IncompleteAnnotationException: g.a.a.n missing element priority
at libcore.reflect.AnnotationFactory.invoke(AnnotationFactory.java:301)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy0.priority(Unknown Source)
at g.a.a.q.a(SubscriberMethodFinder.java:13)
at g.a.a.q.n(SubscriberMethodFinder.java:10)
at g.a.a.q.m(SubscriberMethodFinder.java:4)
at g.a.a.e.M(EventBus.java:2)
at d.e.f.c.t.init(SceneDataManager.java:11)

**Comment by Kashish-Sharma** [comment] 2019-06-22 18:26
When using R8, I'm getting this error:
```
Could not dispatch event: class ABC 
to subscribing class XYZ
```
Without R8, the app's working fine.

I'm using these rules:
```
-keepattributes *Annotation*
-keepclassmembers class * {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
```

**Comment by kutran** [comment] 2019-10-02 11:37
Nothing?  I think R8 is stripping the methods out since nothing is calling it.  I tried @Keep from AndroidX.annotation, but still getting removed.

**Comment by Duna** [comment] 2019-12-29 10:13
[BUG][CRITICAL] . - should be marked as title

**Comment by greenrobot-team** [comment] 2020-01-21 06:58
So I just tried this with a minimal example project, with and without subscriber index. In both cases the `@Subscribe` annotation gets renamed, but all methods annotated with it are kept (e.g. verified using APK Analyzer and actually running the example).
https://github.com/greenrobot-team/greenrobot-examples/tree/master/eventbus

Using Gradle 5.6.4, Android Gradle Plugin 3.5.3 and the ProGuard/R8 rules recommended.

Can any of you share a small example project that has this issue?

**Comment by Duna** [comment] 2020-01-21 07:51
Any news and fixes regarding this CRITICAL issue?

**Comment by greenrobot-team** [comment] 2020-01-21 11:15
@Duna Please read [my recent comment](https://github.com/greenrobot/EventBus/issues/586#issuecomment-576544627).

**Comment by Duna** [comment] 2020-01-21 17:25
@greenrobot-team Please write me an email and ill give you back a medium sized project as an example

**Comment by Duna** [comment] 2020-01-31 16:16
2020-01-31 18:15:51.307 17764-17764/com.dunatv.photosafe E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dunatv.photosafe, PID: 17764
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dunatv.photosafe/com.dunatv.photosafe.photos.cloud.CloudGalleryActivity}: n.a.a.e: Subscriber class com.dunatv.photosafe.photos.cloud.b and its super classes have no public methods with the @Subscribe annotation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: n.a.a.e: Subscriber class com.dunatv.photosafe.photos.cloud.b and its super classes have no public methods with the @Subscribe annotation
        at n.a.a.p.a(SourceFile:67)
        at n.a.a.c.b(SourceFile:140)
        at com.dunatv.photosafe.photos.cloud.b.onCreate(SourceFile:60)
        at android.app.Fragment.performCreate(Fragment.java:2515)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:184)
        at android.app.Activity.performCreate(Activity.java:7809)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by Duna** [comment] 2020-04-01 11:46
Here it is the sample project that proves the EventBus is crashing the app. By default R8 is enabled in Android Studio 3.6.1. ProGuard is not used anymore since is deprecated.

[Sample Project](https://drive.google.com/file/d/1IV92xPTFkLWjDMK9_MylD5J6T9UpABuI/view?usp=sharing)

**Comment by greenrobot-team** [comment] 2022-04-25 11:09
We are using EventBus in an Android project with latest Android tooling, including R8 without issues. Since the latest release also embeds R8 rules this hopefully should no longer be an issue.
https://github.com/greenrobot/EventBus/blob/master/eventbus-android/consumer-rules.pro

**Closed by greenrobot-team** 2022-04-25 11:09 UTC
Labels: more info required

**Comment by pedroAtBU** [comment] 2023-08-11 14:56
> We are using EventBus in an Android project with latest Android tooling, including R8 without issues. Since the latest release also embeds R8 rules this hopefully should no longer be an issue.
> https://github.com/greenrobot/EventBus/blob/master/eventbus-android/consumer-rules.pro

not working for me even with the rules
