### ISSUE TITLE
Pojo Model classes in Proguard

### ISSUE THREAD

**Issue by BigGitWorld** [greenrobot/EventBus#532] opened 2018-06-11 08:06 UTC
Hi.
I'm using EventBus in my android project.
it's working perfectly in debug mode.
Now I'm going to enable proguard to obfuscate my application.
I used the following in proguard-roles.pro : 
```
-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
```
But I received an error that show my pojo classes are "unknown source".
So I think pojo classes must be included in proguard, also.
But I didn't see anyone who keep his/her pojo classes in eventbus from proguard.
Am i making a mistake?

**Comment by greenrobot-team** [comment] 2018-08-27 13:14
Your proguard rules are fine. I can't really say what the issue is without an example project reproducing this. We are not aware of any problems in that regard. 

Closing due to missing details.
-ut

**Closed by greenrobot-team** 2018-08-27 13:14 UTC
